spring:
#  flyway:
#    enabled: true
#    locations: classpath:dbone/migration,classpath:dbtwo/migration
  datasource:
    druid:
      alpha:
        url: jdbc:mysql://localhost:3306/demodb?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false
        username: root
        password: root
        #<!-- 配置监控统计拦截的filters -->
        filters: stat
        #<!-- 配置初始化大小、最小、最大 -->
        initial-size: 1
        min-idle: 1
        max-active: 20
        #<!-- 配置获取连接等待超时的时间 -->
        max-wait: 60000
        #<!-- 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒 -->
        time-between-eviction-runs-millis: 60000
        #<!-- 配置一个连接在池中最小生存的时间，单位是毫秒 -->
        min-evictable-idle-time-millis: 300000
        validation-query: 'select 1'
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        stat-view-servlet:
          enabled: true
          login-username: admin
          login-password: admin
          url-pattern: /druid/*
          reset-enable: false
        connection-properties: 'druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000' 
      beta:
        url: jdbc:mysql://192.168.1.167:3306/demodb?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
        username: root
        password: root
        filters: stat
        initial-size: 1
        min-idle: 1
        max-active: 20
        max-wait: 60000
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        validation-query: 'select 1'
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        connection-properties: 'druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000'
        web-stat-filter:
          enabled: true
          url-pattern: '/*'
          exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
        stat-view-servlet:
          enabled: true
          login-username: admin
          login-password: admin
          reset-enable: false
          url-pattern: /druid/*
